name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B install -DskipTest=true --file pom.xml
    - name: Upload artifacts to github
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/target/*.jar
        retention-day: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: docker image build
      run: docker build -t first-project . 
    - name: docker image push
      env: 
        registry: https://ghcr.io
        username: gopichand2421
        password: ${{ secrets.password }}
        repository: gopichand2421/imagerepo
      run: docker push first-project
    
